# -*- coding: utf-8 -*-
"""cgi_city_data_preprocessing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NJo4z1i99aWEgtWpWKvPvAIAhdzmqN6e

#  处理小区基站工参数据预处理
"""

import numpy as np
import pandas as pd


def read_base_station_info(path, cgi_list, not_include=['地市', '区县', '覆盖场景']):
    data = pd.read_csv(path, index_col='CGI')
    object_cols = data.select_dtypes('object').columns.to_list()
    for i,col in enumerate(object_cols):
        if col in not_include:
            continue
        data = pd.get_dummies(data, prefix=[col], columns=[col], drop_first=True)

    cgi_list = list(set(cgi_list) & set(data.index.unique()))
    return data.loc[cgi_list]


if __name__ == '__main__':
    data = pd.read_csv('./data/cgi_2year_qinghuai.csv', index_col='cgi')
    cgi_list = data.index.unique()

    print(read_base_station_info('./data/剔除冗余特征后全量工参.csv', cgi_list).info())

