# -*- coding: utf-8 -*-
"""45g基站关联.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ows7H2CN19ePNoUhe4bjiofkEg8AErf1
"""

# loading packages
import warnings
warnings.filterwarnings("ignore")

import pickle as pkl
# basic + dates 
import numpy as np
import pandas as pd
from pandas import datetime

# data visualization
import matplotlib.pyplot as plt
import seaborn as sns # advanced vizs

# File system manangement
import os


CITY_NAME = '南京'
cgi_45g = pd.read_csv('../4Gprocessed_data/45G-0424_000000_tmp_hjj1_141_20220424.csv',encoding
='gbk')

cgi_45g.CITY_NAME.unique().tolist()

cgi_45g_ct = cgi_45g.groupby('SECTOR_ID').count()['CGI']
cgi_45g_ct = pd.DataFrame(cgi_45g_ct)

cgi_45g_nj = cgi_45g[cgi_45g['CITY_NAME'] ==CITY_NAME]
cgi_nj_list = cgi_45g_nj.CGI.unique().tolist()
print(CITY_NAME + '包含SECTOR ID的4G和5G CGI总个数为:', len(cgi_nj_list))
cgi_45g_nj.set_index('CGI',inplace = True)

cgi_4g_nj = pd.read_csv('../4Gprocessed_data/cgi_2year_南京.csv',encoding ='gbk')
cgi_4g_nj.set_index('cgi',inplace= True)
cgi_4g_nj_list=cgi_4g_nj.index.unique().tolist()
print("南京4G流量对应的基站总数为：", len(cgi_4g_nj_list))

df_5g_flow = pd.read_csv('../5Gprocessed_data/5G全量数据.csv')

df_5g_flow.set_index('cgi',inplace =True)
df_5g_flow

print("江苏省5G流量中的cgi个数:", len(df_5g_flow.index.unique().tolist()))

cgi_5g = pd.read_csv('../5Gprocessed_data/处理后5G工参.csv')
cgi_5g.set_index('CGI', inplace =True)
cgi_5g_nj = cgi_5g[cgi_5g['城市']=='南京']
cgi_5g_nj_list = cgi_5g_nj.index.unique().tolist()
print("南京5G基站总数为:", len(cgi_5g_nj_list))
cgi_5g_nj

cgi_5j_nj_list = df_5g_flow.join(cgi_5g_nj, how ='inner').index.unique().tolist()

same_cgi_5g = list(set(cgi_5j_nj_list).intersection(set(cgi_nj_list)))

"""# 5G"""

print("江苏省5G流量中的cgi个数:", len(df_5g_flow.index.unique().tolist()))
print("南京5G基站工参总数为:", len(cgi_5g_nj.index.unique().tolist()))
print('江苏省5G流量中对应上南京市5G基站工参的cgi个数为:', len(cgi_5j_nj_list))
print("南京5G流量能对应上SECTOR中基站的数量为:", len(same_cgi_5g), "占比为:", len(same_cgi_5g)/len(same_cgi_5g)*100, "%")
#
#
#
# """# 4G"""
#
# same_cgi = list(set(cgi_4g_nj_list).intersection(set(cgi_nj_list)))
# print('南京包含SECTOR ID的4G和5G CGI总个数为:', len(cgi_nj_list))
# print("南京4G流量对应的基站总数为:", len(cgi_4g_nj_list))
# print("南京4G流量能对应上SECTOR中基站的数量为:", len(same_cgi), "占比为:", len(same_cgi)/len(cgi_4g_nj_list)*100, "%")
#
# path = "/content/drive/Shareddrives/work/无线网智能预测/processed_data/cgi_2year_liuhe.csv"
# df_4g = pd.read_csv(path)
# df_4g = df_4g.rename({'Unnamed: 0': "cgi"}, axis='columns')
# df_4g = df_4g.set_index(["cgi"])
# qinhuai_cgi_list = df_4g.index.unique().tolist()
# print(len(qinhuai_cgi_list))
#
#
#
# df_4g.head()
#
# qinhuai_SECTOR_ID_df = df_4g.join(cgi_45g_nj)
# qinhuai_SECTOR_ID_df.dropna(inplace=True)
#
# len(qinhuai_SECTOR_ID_df.index.unique().tolist())

